#!/usr/bin/env sh

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

pattern='^[a-z0-9-]+\[[0-9]+\]: [A-Z].+$'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo ""
  echo "❌ Invalid commit message."
  echo ""
  echo "Expected:"
  echo "  <category>[<problem-id>]: <problem-title>"
  echo ""
  echo "Examples:"
  echo "  hashing[1]: Two Sum"
  echo "  database[1251]: Average Selling Price"
  echo "  tree[104]: Maximum Depth of Binary Tree"
  echo "  dynamic-programming[70]: Climbing Stairs"
  echo ""
  exit 1
fi

echo "✅ Commit message format valid."